plugins {
    id "com.android.application"
}

android {
    namespace "com.monocosmos.videowallplayer"
    compileSdk 36

    defaultConfig {
        applicationId "com.monocosmos.videowallplayer"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    packaging {
        resources {
            excludes += [
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt"
            ]
        }
    }
}

dependencies {
    implementation "org.videolan.android:libvlc-all:3.7.4"
}
