<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VideoWallPlayerSetup</AssemblyName>
    <RootNamespace>VideoWallPlayer.Setup</RootNamespace>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
    <InformationalVersion>1.0.3</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AssemblyTitle>VideoWallPlayer Installer</AssemblyTitle>
    <Product>VideoWallPlayer</Product>
    <Company>Nodera Software</Company>
    <Copyright>Copyright (C) 2026 Nodera Software</Copyright>
    <ApplicationIcon>..\..\native\VideoWallPlayer.Native\Assets\AppIcon.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\VideoWallPlayer-Windows-Portable-x64.zip" LogicalName="Payload.zip" />
  </ItemGroup>
</Project>
